builds:

  ubuntu-16.04:
    context: /
    dockerfile: Dockerfiles/Ubuntu/16.04/Dockerfile
    pushes:
      - "on_branch:master=didstopia/base:ubuntu-16.04"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Ubuntu."
      - "org.label-schema.version=ubuntu-16.04"
      - "org.label-schema.description=An always up to date base image for Ubuntu."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
  
  nodejs-ubuntu-16.04:
    context: /
    dockerfile: Dockerfiles/Ubuntu/16.04/nodejs/Dockerfile
    depends_on:
      - ubuntu-16.04
    pushes:
      - "on_branch:master=didstopia/base:nodejs-ubuntu-16.04"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Node.js LTS."
      - "org.label-schema.version=nodejs-ubuntu-16.04"
      - "org.label-schema.description=An always up to date base image for Node.js LTS."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"

  steamcmd-ubuntu-16.04:
    context: /
    dockerfile: Dockerfiles/Ubuntu/16.04/steamcmd/Dockerfile
    depends_on:
      - ubuntu-16.04
    pushes:
      - "on_branch:master=didstopia/base:steamcmd-ubuntu-16.04"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for steamcmd."
      - "org.label-schema.version=steamcmd-ubuntu-16.04"
      - "org.label-schema.description=An always up to date base image for steamcmd."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
  
  nodejs-steamcmd-ubuntu-16.04:
    context: /
    dockerfile: Dockerfiles/Ubuntu/16.04/nodejs-steamcmd/Dockerfile
    depends_on:
      - steamcmd-ubuntu-16.04
    pushes:
      - "on_branch:master=didstopia/base:nodejs-steamcmd-ubuntu-16.04"
    labels:
      - "org.label-schema.vendor=Didstopia"
      - "org.label-schema.name=Base Docker image for Node.js LTS and steamcmd."
      - "org.label-schema.version=nodejs-steamcmd-ubuntu-16.04"
      - "org.label-schema.description=An always up to date base image for Node.js LTS and steamcmd."
      - "org.label-schema.url=https://github.com/Didstopia/docker-base-images"
      - "org.label-schema.vcs-url=github.com:Didstopia/docker-base-images.git"
      - "org.label-schema.vcs-ref={fcommitid}"
      - "org.label-schema.schema-version=1.0"
