# Run as root
sudo: required

# No specific environment necessary
language: generic

# Install Docker support
services:
  - docker

# Prepare the environment
before_install:
  - .travis/setup.sh
  - source .travis/update_check.sh

# Build the images
install:
  - .travis/build.sh

# Test and push the images if necessary
script:
  - .travis/test.sh
  - .travis/push.sh

# Only build specific branches
branches:
  only:
    - master
    - development
